version: "3"

services: 
  api:
    build:
      context: .
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    networks:
      - docker-service
    depends_on: 
      - mariadb
    volumes:
      - "./src:/app"

  mariadb:
    image: mariadb:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local